### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by PeterMontague** [dickloraine/EmbedComicMetadata#12]
I get the following error when running the plugin. I'm sure I'm missing something obvious somewhere. I've confirmed that all the correct data is in the comicinfo.xml file and it does change the name and author info in Calibre when it's run, but that's it. I do have all the columns mapped properly as well. I'm stumped (:

calibre, version 3.48.0
ERROR: Unhandled exception: <b>AttributeError</b>:'int' object has no attribute 'decode'

calibre 3.48 embedded-python: True is64bit: True
Darwin-18.6.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.6.0', 'Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.14.5', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 2) && Embed Comic Metadata (1, 4, 0) && Count Pages (1, 8, 2)
Traceback (most recent call last):
File "calibre_plugins.EmbedComicMetadata.main", line 33, in import_to_calibre
File "calibre_plugins.EmbedComicMetadata.main", line 127, in iterate_over_books
File "calibre_plugins.EmbedComicMetadata.main", line 22, in _import_to_calibre
File "calibre_plugins.EmbedComicMetadata.comicmetadata" , line 86, in import_comic_metadata_to_calibre
File "site-packages/calibre/db/cache.py", line 62, in call_func_with_lock
File "site-packages/calibre/db/cache.py", line 1371, in set_metadata
File "site-packages/calibre/db/cache.py", line 1314, in protected_set_field
File "site-packages/calibre/db/cache.py", line 1294, in set_field
File "site-packages/calibre/db/cache.py", line 1115, in set_field
File "site-packages/calibre/db/write.py", line 540, in set_books
File "site-packages/calibre/db/write.py", line 540, in <dictcomp>
File "site-packages/calibre/db/write.py", line 32, in single_text
AttributeError: 'int' object has no attribute 'decode'

**Comment by PeterMontague** [comment]
I got it, the comicvine url custom column wasn't set to XML format.  Thanks so much for this amazing plugin!  I have a lot of work ahead of me now (:
