### ISSUE TITLE
Error when importing a cbr metadata (Not all CBRs have this problem)

### ISSUE THREAD

**Issue by lopiv2** [dickloraine/EmbedComicMetadata#18]
Error when importing metadata in a comic cbr file. Not all CBRs...:

calibre, version 5.11.0
ERROR: Excepción no considerada: <b>AttributeError</b>:'function' object has no attribute 'encode'

calibre 5.11  embedded-python: True is64bit: True
Linux-5.3.0-64-generic-x86_64-with-glibc2.2.5 Linux ('64bit', '')
('Linux', '5.3.0-64-generic', '#58-Ubuntu SMP Fri Jul 10 19:33:51 UTC 2020')
Python 3.8.5
Interface language: es
Successfully initialized third party plugins: Embed Comic Metadata (1, 6, 0) && Manage Series (1, 2, 11)
Traceback (most recent call last):
  File "calibre_plugins.EmbedComicMetadata.ui", line 96, in main_menu_triggered
    import_to_calibre(self, action)
  File "calibre_plugins.EmbedComicMetadata.main", line 32, in import_to_calibre
    iterate_over_books(ia, _import_to_calibre,
  File "calibre_plugins.EmbedComicMetadata.main", line 127, in iterate_over_books
    if should_convert and convert_to_cbz(ia, metadata):
  File "calibre_plugins.EmbedComicMetadata.main", line 162, in convert_to_cbz
    metadata.convert_cbr_to_cbz()
  File "calibre_plugins.EmbedComicMetadata.comicmetadata", line 315, in convert_cbr_to_cbz
    zf.comment = comment.encode("utf-8")
AttributeError: 'function' object has no attribute 'encode'

**Comment by dickloraine** [comment]
Thanks for the bug report. This should be fixed now.
