### ISSUE TITLE
CBR to CBZ Conversion Error

### ISSUE THREAD

**Issue by ecmatthee** [dickloraine/EmbedComicMetadata#24]
Hi, if you could assist it would be appreciated.

I am experiencing error when converting CBR files to CBZ.

Error detail below:

calibre 6.5  embedded-python: False
Linux-5.19.9-arch1-1-x86_64-with-glibc2.36 Linux ('64bit', 'ELF')
('Linux', '5.19.9-arch1-1', '#1 SMP PREEMPT_DYNAMIC Thu, 15 Sep 2022 16:08:26 +0000')
Python 3.10.7
Interface language: None
Successfully initialized third party plugins: Comicvine (0, 14, 1) && Comments Cleaner (1, 7, 3) && Embed Comic Metadata (1, 6, 2) && Job Spy (1, 0, 192) && Modify ePub (1, 7, 3) && Quality Check (1, 12, 0)
Traceback (most recent call last):
  File "calibre_plugins.EmbedComicMetadata.ui", line 98, in main_menu_triggered
    embed_into_comic(self, action)
  File "calibre_plugins.EmbedComicMetadata.main", line 51, in embed_into_comic
    iterate_over_books(ia, _embed_into_comic,
  File "calibre_plugins.EmbedComicMetadata.main", line 127, in iterate_over_books
    if should_convert and convert_to_cbz(ia, metadata):
  File "calibre_plugins.EmbedComicMetadata.main", line 162, in convert_to_cbz
    metadata.convert_cbr_to_cbz()
  File "calibre_plugins.EmbedComicMetadata.comicmetadata", line 314, in convert_cbr_to_cbz
    zf.add_dir(tdir)
AttributeError: 'ZipFile' object has no attribute 'add_dir'

**Comment by dickloraine** [comment]
Thanks for the report, the bug should be fixed now.
